theme: jekyll-theme-midnight
title: "Team TripleAJ CPT"
description: "Frank P Leuck and Judith Sherwood Leuck reunion site and blog."
gitorg: "https://github.com/jm1021/leuck_reunion"
description: "Create Performance Task Site"
google_analytics:
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one