theme: jekyll-theme-midnight
title: "Team TripleAJ CPT"
description: "TripleAJ Create Performance Task site"
gitorg: "https://github.com/Azeem-Khan1/TripleAJv2"
description: "Create Performance Task Site"
google_analytics:
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one